name: Testing_modules
on:
  push:
    branches: 
    - '*'
  pull_request:
    branches:
    - '*'

permissions:
  contents: read

jobs:
  ubuntu_latest_testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: python_install
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run unit tests
        run: python -m unittest
        
  windows_latest_testing:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: python_install
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run unit tests
        run: python -m unittest
        
